extern int clientSocket;
extern int STMboard0_adress;
extern int STMboard1_adress;
extern int STMboard2_adress;
extern int STMboard3_adress;
extern int fd0;
extern int fd1;
extern int fd2;
extern int fd3;